feature 6 - Quest System – Interaction with Database for quests
CSC207-2022F-UofT/course-project-graffiti-alley-mindless-entertainment pull request #116
Opened 2022-12-06 01:58 UTC by evagrafouille

QuestDatabase.json contains the information for the quest (in Json format). QuestData contains all the information required to create a quest. QuestDataFactory creates a QuestData object from a Json file. QuestDataManager looks for the through the QuestDatabase.json to fetch the Quest we are looking through and returns a QuestData object.

Integrated the Quests to the event system.

Remains to be updated: in EncounterEvent, add the quest to the quests undertaken by the player.

Remaining to be done for the quest System:
* QuestFactory
* QuestManager
* QuestMenuState

2022-12-06 02:27 UTC, bw55555 requested changes
using encounter event for quest event violates single responsibility principle - encounter event should be for only battle

2022-12-06 02:27 UTC, bw55555 commented on src/main/java/game_world/objects/events/EncounterEvent.java
> +        } else if (this.encounterType.equals("Quest")) {
Single responsibility principle is violated here
Should be two different classes: EncounterEvent and QuestEvent

2022-12-06 02:27 UTC, bw55555 commented on src/main/resources/EventDatabase.json
> +      "encounter-type": "Quest",
here should just be type: "Quest" instead of repurposing Encounter to also work with Quests

2022-12-06 02:27 UTC, bw55555 commented on src/main/resources/QuestDatabase.json
> +    {
recommend to implement this by {"0": {quest data here}} instead of an array

2022-12-06 02:27 UTC, bw55555 commented on src/main/java/database/factories/EventDataFactory.java
>      public EncounterEventData createEncounterEventData(JSONObject jsonObject) {
should have another class for questEvent

2022-12-07 23:33 UTC, evagrafouille commented
It has been solved with Mahir's pull request, yesterday.

2022-12-07 23:33 UTC, closed without merging