120 implement savableentity for inventory + fix warnings
CSC207-2022F-UofT/course-project-graffiti-alley-mindless-entertainment pull request #121
Opened 2022-12-06 15:09 UTC by juhwansonn

2022-12-06 15:43 UTC, bw55555 requested changes

2022-12-06 15:43 UTC, bw55555 commented on src/main/java/save/SaveInventory.java
> +            return null;
Try not to return null, return empty string instead

2022-12-06 15:43 UTC, bw55555 commented on src/main/java/save/SaveEntityId.java
> +    INVENTORY_ID
perhaps name as INVENTORY instead of INVENTORY_ID?

2022-12-06 21:50 UTC, bw55555 approved these changes
Looks good! Methods tested and looks clean!

2022-12-06 22:17 UTC, mahirhassan-uoft approved these changes

2022-12-06 22:38 UTC, Yasutakahi approved these changes
code looks greate and changes make sense!

2022-12-06 22:50 UTC, mahirhassan-uoft approved these changes

2022-12-06 22:50 UTC, Yasutakahi submitted a review, later dismissed
looks great!!

2022-12-06 22:51 UTC, passionfruitjello submitted a review, later dismissed

2022-12-06 23:29 UTC, bw55555 approved these changes
refactor changes in a later pull request

2022-12-06 23:29 UTC, bw55555 commented on src/main/java/objects/inventory/Inventory.java
> +    public static Item createItem(String level, String itemType) {
perhaps should not be static

2022-12-07 01:05 UTC, marjaleenakiik approved these changes
Changes make sense to fix the warnings and bugs.

2022-12-07 01:06 UTC, merged