eventDatabaseInteractor + textSpeed + text fix
CSC207-2022F-UofT/course-project-graffiti-alley-mindless-entertainment pull request #137
Opened 2022-12-07 06:39 UTC by mahirhassan-uoft

- fixed some text about "You decided to no" :skull:
- added clean architecture stuff to eventManager for clean architecture
- implemented textSpeed to dialogue

2022-12-07 06:51 UTC, bw55555 requested changes

2022-12-07 06:51 UTC, bw55555 commented on src/main/java/game_world/managers/EventDatabaseInteractor.java
> +        if (type.equals("Encounter")) {
should move this method into EventFactory maybe? Makes more sense imo

2022-12-07 06:51 UTC, bw55555 commented on src/main/java/game_world/managers/EventDatabaseInteractor.java
> +    public Event createEvent(ArrayList<Event> eventQueue, String name, boolean exec) {
what is the eventQueue parameter for?

2022-12-07 16:40 UTC, bw55555 commented on src/main/java/game_world/managers/EventDatabaseInteractor.java
> +        if (type.equals("Encounter")) {
never mind, this is probably fine

2022-12-08 15:33 UTC, Yasutakahi approved these changes
I think the changes make sense and the documentation looks good to me!

2022-12-08 17:50 UTC, passionfruitjello approved these changes
looks fine

2022-12-08 17:51 UTC, bw55555 approved these changes
Looks good, no entity code left in use case!

2022-12-08 17:51 UTC, juhwansonn approved these changes

2022-12-08 17:51 UTC, merged