Feature 9 skill system
CSC207-2022F-UofT/course-project-graffiti-alley-mindless-entertainment pull request #37
Opened 2022-11-16 21:30 UTC by charlietaoxl

Created Skill class and Type enum in battle package. Implemented Skill class with setters, getters, and find functions.

2022-11-16 21:36 UTC, Yasutakahi requested changes
You might want to add some doc string but the code itself look very nice to me

2022-11-17 20:11 UTC, marjaleenakiik approved these changes
Code makes sense, and docstrings are included for more complex methods.

2022-11-18 00:34 UTC, juhwansonn reviewed
There is a typo in Skill.java, other than that everything looks good.

2022-11-18 00:34 UTC, juhwansonn commented on src/main/java/objects/battle/Skill.java
> +     * lag; An integer that adds priority to skills
You might want to fix a typo here.

2022-11-18 00:35 UTC, juhwansonn submitted a review, later dismissed

2022-11-18 02:07 UTC, marjaleenakiik approved these changes
Skills look functional, docstrings describe them well.

2022-11-18 14:37 UTC, Yasutakahi approved these changes
doc string is added and looks very nice

2022-11-19 16:52 UTC, bw55555 approved these changes
Entity looks good and follows clean architecture

2022-11-19 22:39 UTC, merged